### ISSUE TITLE
Dashboard fails to start due to Tone Analyzer Argument error

### ISSUE THREAD

**Issue by kkkum** [IBM-Cloud/insurance-bot-dashboard#75]
Using the "Deploy to IBM Cloud" button to deploy the Cloud Insurance Co. Toolchain - https://github.com/IBM-Cloud/insurance-toolchain, the insurance-bot-dashboard container fails to start due to an Argument Error for the Tone Analyzer component. See the `ibmcloud cf logs` output extracted here:
2018-08-20T17:58:43.58+1000 [APP/PROC/WEB/0] OUT > insurance-bot-dashboard@0.1.0 start /home/vcap/app
   2018-08-20T17:58:43.58+1000 [APP/PROC/WEB/0] OUT > better-npm-run start
   2018-08-20T17:58:43.88+1000 [APP/PROC/WEB/0] OUT running better-npm-run in /home/vcap/app
   2018-08-20T17:58:43.91+1000 [APP/PROC/WEB/0] OUT Executing script: start
   2018-08-20T17:58:43.91+1000 [APP/PROC/WEB/0] OUT to be executed: babel-node bin/server
   2018-08-20T17:58:45.94+1000 [APP/PROC/WEB/0] ERR Mon, 20 Aug 2018 07:58:45 GMT app:config Creating default configuration.
   2018-08-20T17:58:46.04+1000 [APP/PROC/WEB/0] ERR Mon, 20 Aug 2018 07:58:46 GMT app:config Looking for environment overrides for NODE_ENV "production".
   2018-08-20T17:58:46.23+1000 [APP/PROC/WEB/0] ERR Mon, 20 Aug 2018 07:58:46 GMT app:config Found overrides, applying to default configuration.
   2018-08-20T17:58:47.99+1000 [APP/PROC/WEB/0] ERR Mon, 20 Aug 2018 07:58:47 GMT app:webpack:config Create configuration.
   2018-08-20T17:58:47.99+1000 [APP/PROC/WEB/0] ERR Mon, 20 Aug 2018 07:58:47 GMT app:webpack:config Enable plugins for production (OccurenceOrder, Dedupe, UglifyJS, & GZip).
   2018-08-20T17:58:48.16+1000 [APP/PROC/WEB/0] ERR Mon, 20 Aug 2018 07:58:48 GMT app:webpack:config Apply ExtractTextPlugin to CSS loaders.
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/watson-developer-cloud/lib/base_service.js:73
   2018-08-20T17:58:49.09+1000 [API/2] OUT Process has crashed with type: "web"
   2018-08-20T17:58:49.10+1000 [API/2] OUT App instance exited with guid 93467afa-05c8-41f7-b972-02ec28dce85f payload: {"instance"=>"55f88f5c-0d1b-450f-4d33-0f59", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1", "crash_count"=>11, "crash_timestamp"=>1534751929069148548, "version"=>"b769c723-07c7-4a26-80d8-42c437220aa0"}
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR       throw new Error('Argument error: username and password are required unless use_unauthenticated is set');
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR       ^
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR Error: Argument error: username and password are required unless use_unauthenticated is set
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at ToneAnalyzerV3.BaseService.initCredentials (/home/vcap/app/node_modules/watson-developer-cloud/lib/base_service.js:73:13)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at ToneAnalyzerV3.BaseService (/home/vcap/app/node_modules/watson-developer-cloud/lib/base_service.js:44:18)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at new ToneAnalyzerV3 (/home/vcap/app/node_modules/watson-developer-cloud/tone-analyzer/v3.js:31:15)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Object.value (/home/vcap/app/node_modules/watson-developer-cloud/index.js:91:14)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/server/logs.js:80:25)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:556:32)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at loader (/home/vcap/app/node_modules/babel-register/lib/node.js:144:5)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Object.require.extensions.(anonymous function) [as .js] (/home/vcap/app/node_modules/babel-register/lib/node.js:154:7)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Module.load (module.js:473:32)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:432:12)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:424:3)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Module.require (module.js:483:17)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at require (internal/module.js:20:19)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/server/main.js:11:1)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:556:32)
   2018-08-20T17:58:48.98+1000 [APP/PROC/WEB/0] ERR     at loader (/home/vcap/app/node_modules/babel-register/lib/node.js:144:5)
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! Linux 4.4.0-109-generic
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! node v6.7.0
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! npm  v3.10.10
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! insurance-bot-dashboard@0.1.0 start: `better-npm-run start`
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR!
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! Failed at the insurance-bot-dashboard@0.1.0 start script 'better-npm-run start'.
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! If you do, this is most likely a problem with the insurance-bot-dashboard package,
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! not with npm itself.
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! Tell the author that this fails on your system:
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR!     better-npm-run start
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! You can get information on how to open an issue for this project with:
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR!     npm bugs insurance-bot-dashboard
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! Or if that isn't available, you can get their info via:
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR!     npm owner ls insurance-bot-dashboard
   2018-08-20T17:58:49.01+1000 [APP/PROC/WEB/0] ERR npm ERR! There is likely additional logging output above.
   2018-08-20T17:58:49.03+1000 [APP/PROC/WEB/0] ERR npm ERR! Please include the following file with any support request:
   2018-08-20T17:58:49.03+1000 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/npm-debug.log
   2018-08-20T17:58:49.05+1000 [APP/PROC/WEB/0] OUT Exit status 1
   2018-08-20T17:58:49.05+1000 [CELL/SSHD/0] OUT Exit status 0
   2018-08-20T17:58:49.07+1000 [CELL/0] OUT Cell ff271f7c-9ed4-486a-9fba-515132fc5f18 stopping instance 55f88f5c-0d1b-450f-4d33-0f59
   2018-08-20T17:58:49.07+1000 [CELL/0] OUT Cell ff271f7c-9ed4-486a-9fba-515132fc5f18 destroying container for instance 55f88f5c-0d1b-450f-4d33-0f59
   2018-08-20T17:58:49.30+1000 [PROXY/0] OUT Exit status 137
   2018-08-20T17:58:51.12+1000 [CELL/0] OUT Cell ff271f7c-9ed4-486a-9fba-515132fc5f18 successfully destroyed container for instance 55f88f5c-0d1b-450f-4d33-0f59

**Comment by l2fprod** [comment]
@kkkum 

a few things to check:

1/ was the Tone Analyzer service correctly created by the toolchain?
2/ if you look at the application details in the IBM Cloud console, under Runtimes / Environment variables, do you see the "tone_analyzer" credentials in VCAP_SERVICES?

![image](https://user-images.githubusercontent.com/12746550/44668465-c1620480-aa1d-11e8-9726-00b7918d656f.png)

3/ which version of watson-developer-cloud sdk is being picked up? Look at the logs during the app staging - mine uses 2.42.0

**Comment by kkkum** [comment]
@l2fprod thanks for the comments.

1/ Yes, the Tone Analyzer was correctly created.
<img width="1139" alt="insurance tone analyzer service" src="https://user-images.githubusercontent.com/15808054/44697827-e3f92980-aac0-11e8-82f0-0c5cce852fb5.png">


2/ Yes, the "tone_analyzer" credentials are in the VCAP_SERVICES of the insurance-bot-dashboard app.
<img width="1114" alt="insurance dashboard runtime" src="https://user-images.githubusercontent.com/15808054/44697638-fa52b580-aabf-11e8-8a60-f1e55a0c1feb.png">

3/ In the app staging logs, the SDK `watson-developer-cloud@2.42.0` was picked up.

Any ideas how to further troubleshoot and resolve this?

**Comment by l2fprod** [comment]
the screenshot 2/ helps. The tone_analyzer being provisioned use the new IAM api key but the code in https://github.com/IBM-Cloud/insurance-bot-dashboard/blob/dev/server/logs.js#L71 still expects a username/password. We will fix this

**Comment by l2fprod** [comment]
this commit https://github.com/IBM-Cloud/insurance-bot-dashboard/commit/938dd7c3c15ec929eb08db30a56b6280e8dbe4a2 fixes the issue

**Comment by kkkum** [comment]
Thanks for the fix, @l2fprod !
